config/routes.rb
Rails.application.routes.draw do
  get 'herbs' => 'herb#index', as: 'herbs'
  get 'herbs/new' => 'herb#new', as: 'new_herb'
  get 'herbs/:id' => 'herb#show', as: 'herb'
  post 'herbs' => 'herb#create'
  get 'herb/:id/edit' => 'herb#edit', as: 'edit_herb'
  patch 'herbs/:id' => 'herb#update'
  delete 'herb/:id' => 'herb#destroy', as: 'delete_herb'
  root 'herb#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/herb.rb
class Herb < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/herb_controller.rb
class HerbController < ApplicationController

  def index 
    @herbs = Herb.all
  end

  def show
    @herb = Herb.find(params[:id])
  end

  def new
    @herb = Herb.new 
  end

  def create
    @herb = Herb.create(herb_params)
    if @herb.valid?
      redirect_to herbs_path
    end
  end

  def edit
    @herb = Herb.find(params[:id])
  end

  def update
    @herb = Herb.find(params[:id])
    @herb.update(herb_params)
    if @herb.valid?
      redirect_to herb_path(@herb) 
    end
  end

  def destroy
    @herb = Herb.find(params[:id])
    if @herb.destroy
      redirect_to herbs_path
    end
  end

  # strong params
  private
  def herb_params
    params.require(:herb).permit(:name, :watered) 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/herb/edit.html.erb
<h3>Edit Herb</h3>

<%= form_with model: @herb, method: :patch do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <br />
  <%= form.radio_button :watered, "yes" %>
  <%= form.label :watered, "Herb Is Watered" %>
  <br />
  <%= form.radio_button :watered, "no" %>
  <%= form.label :watered, "Herb Not Watered" %>
  <br />
  <%= form.submit "Edit Herb" %>
<% end %>
<br />
<p><%= link_to 'Back to Main Page', herbs_path %></p>

app/views/herb/index.html.erb
<h1>Herb Garden App</h1>

<ul>
  <% @herbs.each do |herb| %>
    <li><%= link_to herb.name, herb_path(herb) %></li>
  <% end %>
</ul>
<br />
<p><%= link_to 'Add a New Herb', new_herb_path %></p>

app/views/herb/new.html.erb
<h3>Add a New Herb</h3>

<%= form_with model: @herb do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <br />
  <%= form.radio_button :watered, "yes" %>
  <%= form.label :watered, "Herb Is Watered" %>
  <br />
  <%= form.radio_button :watered, "no" %>
  <%= form.label :watered, "Herb Not Watered" %>
  <br />
  <%= form.submit "Add Herb" %>
<% end %>
<br />
<p><%= link_to 'Back to Main Page', herbs_path %></p>

app/views/herb/show.html.erb
<h3>Herb Data</h3>

<p>Herb: <%= @herb.name %></p>
<p>Is watered: <%= @herb.watered %></p>
<br />
<p><%= link_to 'Edit Herb', edit_herb_path(@herb) %></p>
<%= button_to 'Delete Herb', delete_herb_path(@herb), method: :delete, data: { confirm: "Are you sure?" } %>
<p><%= link_to 'Back to Main Page', herbs_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFullStack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>